[phases]
setup = "nix-env -iA nixpkgs.nodejs-18_x nixpkgs.python39"
install-backend = "cd backend && npm install"
install-frontend = "cd frontend && npm install"
build-frontend = "cd frontend && npm run build"
start-backend = "cd backend && node server.js"

[dependencies]
system = [
  "ffmpeg",
  "yt-dlp"
]

[directories]
include = [
  "frontend/",
  "backend/",
  ".nixpacks.toml"
]

[variables]
NODE_ENV = "production"
YOUTUBE_DL_SKIP_PYTHON_CHECK = "1"
