[phases.setup]
# Install root dependencies
run = "npm install"
run = "python3 --version && npm install"


[phases.install]
# Install frontend and backend dependencies
commands = [
  "npm install --prefix frontend",
  "npm install --prefix backend"
]

[phases.build]
# Build the React frontend
commands = ["npm run build --prefix frontend"]

[phases.start]
# Start the backend server and serve the frontend
commands = ["node backend/server.js"]

[dependencies]
packages = ["python3"]
 cache = true

[variables]

NODE_ENV = "production"
PORT = "4000"
FRONTEND_URL = "https://lyrics-video-production.up.railway.app"
REACT_APP_API_URL = "/api"
YOUTUBE_DL_SKIP_PYTHON_CHECK = "1"